### ISSUE TITLE
Bottom part has no solution

### ISSUE THREAD

**Issue by lindseyberlin** [learn-co-curriculum/dsc-multiple-linear-regression-statsmodels-lab#4]
There's a question at the bottom of this lab that isn't answered in the solution.

I added a branch to this repo with my workthrough, but there are some caveats:
- I changed the way you transform the y value. Before, the lab solution had you both logging and standard scaling the y column. I just log transformed it to make the y more normal (no point in scaling it that I can think of)
- I also used sklearn's StandardScaler to normalize instead of doing it by hand with that normalize function they defined in the lab solution. This way, I could just apply the already-fit StandardScaler to the new row (way easier than the alternative)

**Comment by hoffm386** [comment]
Should be resolved by https://github.com/learn-co-curriculum/dsc-multiple-linear-regression-statsmodels-lab/commit/8e63bbd8c8e0d74ffca4eba55894325fe0360f8a (went ahead and added the solution from your branch, with slight tweaks to avoid using `StandardScaler`), thanks for flagging!
